server:
  port: 8201
spring:
  profiles: dev   #开发环境
  application:
    name: microservice-config-client1
---
server:
  port: 8202
spring:
  profiles: test   #测试环境
  application:
    name: microservice-config-client3